### ISSUE TITLE
Does MOI.submit() only return MOI.HEURISTIC_SOLUTION_UNKNOWN in heuristic callback?

### ISSUE THREAD

**Issue by mikeKAH** [jump-dev/CPLEX.jl#287]
The question refers to how I understand line 222 in the MOI_callbacks.jl file. 

I also tried to pass a known optimal solution in a callback to my test model, and obtained MOI.HEURISTIC_SOLUTION_UNKNOWN. (cplex 12.9, julia 1.3.1, JuMP 0.21.1)

Thanks in advance.

**Comment by odow** [comment]
We return `HEURISTIC_SOLUTION_UNKNOWN` because I'm unaware how to confirm if CPLEX accepted or rejected the provided heuristic solution:
https://github.com/JuliaOpt/CPLEX.jl/blob/2756458f5f6c02b784e5c2fb4594c930d6febf60/src/MOI/MOI_callbacks.jl#L219-L223

Here is the MOI documentation: https://www.juliaopt.org/MathOptInterface.jl/stable/apireference/#MathOptInterface.HeuristicSolutionStatus

**Comment by mikeKAH** [comment]
Sorry I don't know that either. I've never used a heuristic callback with the C API before. I only found [this function](https://www.ibm.com/support/knowledgecenter/en/SSSA5P_12.9.0/ilog.odms.cplex.help/refcallablelibrary/mipapi/setheuristiccallbackfunc.html?pos=2) (I don't know if that helps)
